name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.30
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
    runs-on: ${{ matrix.os }}
    name:  ${{ matrix.browser }} on ${{ matrix.os }}
    steps:
    - uses: microsoft/playwright-github-action@v1
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Test
      env:
        BROWSER: ${{ matrix.browser }}
      run: go test -v -covermode atomic -coverprofile=covprofile  --race .
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
  test-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: microsoft/playwright-github-action@v1
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run examples
      run: xvfb-run for dir in examples/*; do go run ${dir}/main.go; done