name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
    runs-on: ${{ matrix.os }}
    name:  ${{ matrix.browser }} on ${{ matrix.os }}
    steps:
    - uses: microsoft/playwright-github-action@v1
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.1
      id: go
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Test
      env:
        BROWSER: ${{ matrix.browser }}
      run: go test -v -covermode atomic -coverprofile=covprofile --race ./...
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: go run github.com/mattn/goveralls -coverprofile=covprofile -package="github.com/mxschmitt/playwright-go" -service=github -parallel -flagname="${{ matrix.os }}-${{ matrix.browser }}"
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.1
      id: go
    - name: Finish
      run: go run github.com/mattn/goveralls -service=github -parallel-finish
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: microsoft/playwright-github-action@v1
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.1
      id: go
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run examples
      run: xvfb-run bash -c "for dir in examples/*; do go run \$dir/main.go; done"
