name: Verify Types
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.1
      - name: Install Browsers
        run: go run scripts/installBrowsers.go
      - name: Regenerate APIs
        run: scripts/generate_api.sh
      - name: Verify API is up to date
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "ERROR: generated interfaces differ from the current sources:"
            git diff
            exit 1
          fi